// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tourist.Infrastructure;

#nullable disable

namespace Tourist.Infrastructure.Migrations
{
    [DbContext(typeof(TouristContext))]
    [Migration("20250531152344_Update")]
    partial class Update
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TourModelTouristModel", b =>
                {
                    b.Property<Guid>("TouristsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ToursId")
                        .HasColumnType("uuid");

                    b.HasKey("TouristsId", "ToursId");

                    b.HasIndex("ToursId");

                    b.ToTable("TourModelTouristModel");
                });

            modelBuilder.Entity("Tourist.Infrastructure.Models.AgentModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Position")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("Tourist.Infrastructure.Models.BookingModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("MovieTitle")
                        .HasColumnType("text");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("ShowTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Tourist.Infrastructure.Models.PassportModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Number")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Passports");
                });

            modelBuilder.Entity("Tourist.Infrastructure.Models.TourModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Destination")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tours");
                });

            modelBuilder.Entity("Tourist.Infrastructure.Models.TourPackageModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Genre")
                        .HasColumnType("text");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TourPackages");
                });

            modelBuilder.Entity("Tourist.Infrastructure.Models.TouristModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("FavoriteGenre")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid?>("PassportId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PassportId")
                        .IsUnique();

                    b.ToTable("Tourists", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Tourist.Infrastructure.Models.GuideModel", b =>
                {
                    b.HasBaseType("Tourist.Infrastructure.Models.TouristModel");

                    b.Property<string>("LicenseNumber")
                        .HasColumnType("text");

                    b.ToTable("Guides", (string)null);
                });

            modelBuilder.Entity("TourModelTouristModel", b =>
                {
                    b.HasOne("Tourist.Infrastructure.Models.TouristModel", null)
                        .WithMany()
                        .HasForeignKey("TouristsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tourist.Infrastructure.Models.TourModel", null)
                        .WithMany()
                        .HasForeignKey("ToursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tourist.Infrastructure.Models.TouristModel", b =>
                {
                    b.HasOne("Tourist.Infrastructure.Models.PassportModel", "Passport")
                        .WithOne("Tourist")
                        .HasForeignKey("Tourist.Infrastructure.Models.TouristModel", "PassportId");

                    b.Navigation("Passport");
                });

            modelBuilder.Entity("Tourist.Infrastructure.Models.GuideModel", b =>
                {
                    b.HasOne("Tourist.Infrastructure.Models.TouristModel", null)
                        .WithOne()
                        .HasForeignKey("Tourist.Infrastructure.Models.GuideModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tourist.Infrastructure.Models.PassportModel", b =>
                {
                    b.Navigation("Tourist");
                });
#pragma warning restore 612, 618
        }
    }
}
